// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// AuthService is the Schema for the authservices API
type AuthService struct {
	pulumi.CustomResourceState

	ApiVersion pulumi.StringPtrOutput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrOutput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrOutput `pulumi:"metadata"`
	// AuthServiceSpec defines the desired state of AuthService
	Spec AuthServiceSpecPtrOutput `pulumi:"spec"`
}

// NewAuthService registers a new resource with the given unique name, arguments, and options.
func NewAuthService(ctx *pulumi.Context,
	name string, args *AuthServiceArgs, opts ...pulumi.ResourceOption) (*AuthService, error) {
	if args == nil {
		args = &AuthServiceArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("getambassador.io/v2")
	args.Kind = pulumi.StringPtr("AuthService")
	var resource AuthService
	err := ctx.RegisterResource("kubernetes:getambassador.io/v2:AuthService", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthService gets an existing AuthService resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthService(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthServiceState, opts ...pulumi.ResourceOption) (*AuthService, error) {
	var resource AuthService
	err := ctx.ReadResource("kubernetes:getambassador.io/v2:AuthService", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthService resources.
type authServiceState struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AuthServiceSpec defines the desired state of AuthService
	Spec *AuthServiceSpec `pulumi:"spec"`
}

type AuthServiceState struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AuthServiceSpec defines the desired state of AuthService
	Spec AuthServiceSpecPtrInput
}

func (AuthServiceState) ElementType() reflect.Type {
	return reflect.TypeOf((*authServiceState)(nil)).Elem()
}

type authServiceArgs struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AuthServiceSpec defines the desired state of AuthService
	Spec *AuthServiceSpec `pulumi:"spec"`
}

// The set of arguments for constructing a AuthService resource.
type AuthServiceArgs struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AuthServiceSpec defines the desired state of AuthService
	Spec AuthServiceSpecPtrInput
}

func (AuthServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authServiceArgs)(nil)).Elem()
}

type AuthServiceInput interface {
	pulumi.Input

	ToAuthServiceOutput() AuthServiceOutput
	ToAuthServiceOutputWithContext(ctx context.Context) AuthServiceOutput
}

func (*AuthService) ElementType() reflect.Type {
	return reflect.TypeOf((*AuthService)(nil))
}

func (i *AuthService) ToAuthServiceOutput() AuthServiceOutput {
	return i.ToAuthServiceOutputWithContext(context.Background())
}

func (i *AuthService) ToAuthServiceOutputWithContext(ctx context.Context) AuthServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthServiceOutput)
}

type AuthServiceOutput struct {
	*pulumi.OutputState
}

func (AuthServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AuthService)(nil))
}

func (o AuthServiceOutput) ToAuthServiceOutput() AuthServiceOutput {
	return o
}

func (o AuthServiceOutput) ToAuthServiceOutputWithContext(ctx context.Context) AuthServiceOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(AuthServiceOutput{})
}
