apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app: gloo
        gloo: rbac
    name: gloo-resource-reader-gloo-system
rules:
    - apiGroups:
        - gloo.solo.io
        - enterprise.gloo.solo.io
      resources:
        - upstreams
        - upstreamgroups
        - proxies
        - authconfigs
      verbs:
        - get
        - list
        - watch
        - update
    - apiGroups:
        - ratelimit.solo.io
      resources:
        - ratelimitconfigs
        - ratelimitconfigs/status
      verbs:
        - get
        - list
        - watch
        - update
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - update
