apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    annotations:
        helm.sh/hook: crd-install
    name: ratelimitconfigs.ratelimit.solo.io
spec:
    group: ratelimit.solo.io
    names:
        kind: RateLimitConfig
        listKind: RateLimitConfigList
        plural: ratelimitconfigs
        shortNames:
            - rlc
        singular: ratelimitconfig
    scope: Namespaced
    subresources:
        status: {}
    versions:
        - name: v1alpha1
          served: true
          storage: true
