// Code generated by "stringer -type=AccessMode -linecomment"; DO NOT EDIT.

package persistence

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessModeRWO-0]
	_ = x[AccessModeROX-1]
	_ = x[AccessModeRWX-2]
}

const _AccessMode_name = "ReadWriteOnceReadOnlyManyReadWriteMany"

var _AccessMode_index = [...]uint8{0, 13, 25, 38}

func (i AccessMode) String() string {
	if i < 0 || i >= AccessMode(len(_AccessMode_index)-1) {
		return "AccessMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessMode_name[_AccessMode_index[i]:_AccessMode_index[i+1]]
}
