// Code generated by "stringer -type=StorageClass -linecomment"; DO NOT EDIT.

package persistence

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StorageClassLocalPath-0]
}

const _StorageClass_name = "local-path"

var _StorageClass_index = [...]uint8{0, 10}

func (i StorageClass) String() string {
	if i < 0 || i >= StorageClass(len(_StorageClass_index)-1) {
		return "StorageClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageClass_name[_StorageClass_index[i]:_StorageClass_index[i+1]]
}
