###
##
# * TASKFILE
#   https://taskfile.dev
#
version: 3


vars:

  name:                     kube

  domain:                   "thesym.site"

  message:                  tasks for {{.name}}


tasks:

  taskDebug:
    desc: show all variables in Taskfile
    cmds:
      - |
        echo -e \
        "\n{{range $key, $value := .}} {{$key }}:  \e[92m{{$value}}\e[0m\n {{end}}\n"
    silent: true


  default:
    desc: display info
    cmds:
      - |
        echo -e \
        "\n{{.message}}\n"
      - |
        go-task -l
    silent: true


###
##
# ** SEQUENCE
#
#
  0:
    desc: ( clusterCreateDev )
    cmds:
      - task: clusterCreateDev
    silent: true


  1:
    desc: ( pulumiLogin )
    cmds:
      - task: pulumiLogin
    silent: true


  2:
    desc: ( pulumiUp )
    cmds:
      - task: pulumiUp
    silent: true
  4:
    desc: ( clusterDelete )
    cmds:
      - task: clusterDelete
    silent: true


###
##
# ** ALPHABETICAL
#
  # TASK:
  #   desc: DESCRIPTION
  #   cmds:
  #     - |
  #       SHELL-COMMAND WITH \
  # 	  {{.VARIABLE}}
  #   silent: true


  clusterCreateDev:
    desc: create a dev-cluster for {{.domain}}
    cmds:
      - |
        k3d cluster create \
        {{.name}}-dev \
        --no-lb \
        --k3s-server-arg '--no-deploy=traefik' \
        --port 32080:30080 \
        --port 32443:30443


    silent: true
        ### OLD
        # k3d cluster create \
        #         {{.nodeName}} \
        #   --api-port 64433 \
        #         -p 80:80@server[0] \
        #   -p 443:443@server[0] \
        #   -p 22:22@server[0] \
        #   -p 993:993@server[0] \
        #   -p 25:25@server[0] \
        #   -p 587:587@server[0] \
        #   -p 30001:30001@server[0] \
        #   -p 30002:30002@server[0] \
        #   -p 30003:30003@server[0] \
        #   -p 30004:30004@server[0] \
        #   -p 30005:30005@server[0] \
        #   -p 30053:30053/udp@server[0] \
        #   -p 30054:30054@server[0] \
        #   --k3s-server-arg --tls-san="${KUBE_HOST_EXTERNAL_IP}" \
        #   --k3s-server-arg --tls-san="thesym.site" \
        #   --k3s-server-arg --no-deploy="traefik" \
        #   --volume /home/frank/k3s/PERSISTENCE:/PERSISTENCE \

  clusterCreateStage:
    desc: create a staging-cluster for {{.domain}}
    cmds:
      - |
        k3d cluster create \
        {{.name}}-stage \
        --no-lb \
        --k3s-server-arg '--no-deploy=traefik' \
        --port 31080:30080 \
        --port 31443:30443


  clusterDeleteDev:
    desc: delete the dev-cluster
    cmds:
      - |
        k3d cluster delete {{.name}}-dev
    silent: true


  clusterDeleteStage:
    desc: delete the staging-cluster
    cmds:
      - |
        k3d cluster delete {{.name}}-stage
    silent: true


  pulumiLogin:
    desc: make pulumi independent of pulumi.com
    cmds:
      - |
        # pulumi login --local
        pulumi login file://$XDG_STATE_HOME/pulumi
    silent: true


  pulumiNew:
    desc: create a new pulumiProject
    cmds:
      - |
        mkdir {{.nameSpace}}
        cd {{.nameSpace}}
        pulumi new kubernetes-go
    silent: true


  pulumiUp:
    desc: apply main.go
    cmds:
      - |
        summon --up bash -c 'PULUMI_CONFIG_PASSPHRASE=${PULUMI_CONFIG_PASSPHRASE} pulumi up'

    silent: true


  pulumiConfigExample:
    desc: change pulumiConfig
    cmds:
      - |
        cd test
        pulumi config set isContaineredCluster true
    silent: true


  # TaskComposed:
  #   desc: (TASK + TASK)
  #   cmds:
  #     - task: TASK
  #     - task: TASK
  #   silent: true
