###
##
# * TASKFILE
#   https://taskfile.dev
#
version: 3


vars:

  red:           "\e[31m"
  redLight:      "\e[91m"
  green:         "\e[32m"
  greenLight:    "\e[92m"
  yellow:        "\e[33m"
  yellowLight:   "\e[93m"
  blue:          "\e[34m"
  blueLight:     "\e[94m"
  magenta:       "\e[35m"
  magentaLight:  "\e[95m"
  cyan:          "\e[36m"
  cyanLight:     "\e[96m"

  black:         "\e[30m"
  grayDark:      "\e[90m"
  grayLight:     "\e[37m"
  white:         "\e[97m"

  reset:         "\e[0m"

  name:                     kube

  domain:                   "thesym.site"

  message:                  tasks for {{.name}}


tasks:

  taskDebug:
    desc: show all variables in Taskfile
    cmds:
      - |
        echo -e \
        "\n{{range $key, $value := .}} {{$key }}:  \e[92m{{$value}}\e[0m\n {{end}}\n"
    silent: true


  default:
    desc: display info
    cmds:
      - |
        echo -e \
        "\n{{.message}}\n"
      - |
        go-task -l
    silent: true


###
##
# ** SEQUENCE
#
#
  0:
    desc: ( pulumiLogin )
    cmds:
      - task: pulumiLogin
    silent: true


  1d:
    desc: ( clusterCreateDev )
    cmds:
      - task: clusterCreateDev
    silent: true


  2d:
    desc: ( pulumiStackInitDev )
    cmds:
      - task: pulumiStackInitDev
    silent: true


  3d:
    desc: ( pulumiUpDev )
    cmds:
      - task: pulumiUpDev
    silent: true


  4d:
    desc: ( pulumiStackDeleteDev   - {{.red}}ATTENTION{{.reset}} {{.blue}}Pulumi.kube-dev.yaml{{.reset}}   has to be restored with {{.yellow}}git{{.reset}} )
    cmds:
      - task: pulumiStackDeleteDev
    silent: true


  5d:
    desc: ( clusterDeleteDev )
    cmds:
      - task: clusterDeleteDev
    silent: true


  1s:
    desc: ( clusterCreateStage )
    cmds:
      - task: clusterCreateStage
    silent: true


  2s:
    desc: ( pulumiStackInitStage )
    cmds:
      - task: pulumiStackInitStage
    silent: true


  3s:
    desc: ( pulumiUpStage )
    cmds:
      - task: pulumiUpStage
    silent: true


  4s:
    desc: ( pulumiStackDeleteStage - {{.red}}ATTENTION{{.reset}} {{.blue}}Pulumi.kube-stage.yaml{{.reset}} has to be restored with {{.yellow}}git{{.reset}} )
    cmds:
      - task: pulumiStackDeleteStage
    silent: true


  5s:
    desc: ( clusterDeleteStage )
    cmds:
      - task: clusterDeleteStage
    silent: true


  c:
    desc: ( colorDisplay )
    cmds:
      - task:  colorDisplay
    silent: true



###
##
# ** ALPHABETICAL
#
  clusterCreateDev:
    desc: create a dev-cluster     for {{.domain}}
    cmds:
      - |
        k3d cluster create \
        {{.name}}-dev \
        --k3s-arg "--disable=traefik@server:0" \
        --volume $XDG_STATE_HOME/kube/persistence/dev:/srv/kube/persistence/dev \
        --port "32000-32767:30000-30767@server:0"
    silent: true


  clusterCreateStage:
    desc: create a staging-cluster for {{.domain}}
    cmds:
      - |
        k3d cluster create \
        {{.name}}-stage \
        --k3s-arg "--disable=traefik@server:0" \
        --volume $XDG_STATE_HOME/kube/persistence/stage:/srv/kube/persistence/stage \
        --port "31000-31767:30000-30767@server:0"
    silent: true


  clusterDeleteDev:
    desc: delete the dev-cluster
    cmds:
      - |
        k3d cluster delete {{.name}}-dev
    silent: true


  clusterDeleteStage:
    desc: delete the staging-cluster
    cmds:
      - |
        k3d cluster delete {{.name}}-stage
    silent: true


  pulumiDebugOn:
    desc: switch on  debug mode
    cmds:
      - go build -gcflags '-N -l' -o pulumi-main main.go
      - |
        if [[ -f "PulumiDEBUG.yaml" ]]; then
        mv Pulumi{,ORIG}.yaml
        mv Pulumi{DEBUG,}.yaml
        fi
      - echo -e ""
      - echo -e "  run"
      - echo -e "  {{.blue}}p{,S,PROD} up -c debugMode=true{{.reset}}"
      - echo -e "  run"
      - echo -e "  {{.blue}}ps pulumi-main | awk '/pulumi-main$/{print \$1}' | xsel -b{{.reset}}"
      - echo -e ""
      - echo -e "  {{.yellow}}set breakpoint on RunInDebugMode-Loop{{.reset}}"
      - echo -e "  {{.yellow}}attach with 'Go Attach Executable Configuration': yank the pID{{.reset}}"
      - echo -e "  {{.yellow}}set debugReady=true{{.reset}}"
      - echo -e ""
      - echo -e "  {{.green}}debug{{.reset}}"
      - echo -e ""
    silent: true


  pulumiDebugOff:
    desc: switch off debug mode
    cmds:
      - |
        if [[ -f "PulumiORIG.yaml" ]]; then
        mv Pulumi{,DEBUG}.yaml
        mv Pulumi{ORIG,}.yaml
        fi
      - echo -e ""
      - echo -e "  run"
      - echo -e "  {{.blue}}p{,S,PROD} up -c debugMode=false{{.reset}}"
      - echo -e ""
    silent: true


  pulumiLogin:
    desc: make pulumi independent of pulumi.com
    cmds:
      - |
        # pulumi login --local
        pulumi login file://$XDG_STATE_HOME/pulumi
    silent: true


  pulumiNew:
    desc: create a new pulumiProject
    cmds:
      - |
        mkdir {{.nameSpace}}
        cd {{.nameSpace}}
        pulumi new kubernetes-go
    silent: true


  pulumiUpDev:
    desc: |-
      apply the kube-dev-stack   to the specified cluster ( {{.blue}}Pulumi.kube-dev.yaml{{.reset}}:   {{.magenta}}kubernetes:context:{{.reset}} )
    cmds:
      - |
        summonPulumi dev up --emoji
    silent: true


  pulumiUpStage:
    desc: |-
      apply the kube-stage-stack to the specified cluster ( {{.blue}}Pulumi.kube-stage.yaml{{.reset}}: {{.magenta}}kubernetes:context:{{.reset}} )
    cmds:
      - |
        summonPulumi stage up --emoji
    silent: true


  pulumiConfigExample:
    desc: change pulumiConfig
    cmds:
      - |
        cd test
        pulumi config set isContaineredCluster true
    silent: true


  pulumiStackInitDev:
    desc: create a pulumi-stack for the dev-cluster     for {{.domain}}
    cmds:
      - |
        summonPulumi dev stack init --secrets-provider=passphrase --emoji kube-dev
    silent: true


  pulumiStackInitStage:
    desc: create a pulumi-stack for the staging-cluster for {{.domain}}
    cmds:
      - |
        summonPulumi stage stack init --secrets-provider=passphrase --emoji kube-stage
    silent: true


  pulumiStackInitProd:
    desc: create a pulumi-stack for the prod-cluster    for {{.domain}}
    cmds:
      - |
        summonPulumi prod stack init --emoji kube-prod
    silent: true


  pulumiStackDeleteDev:
    desc: delete the pulumi-stack for the dev-cluster     for {{.domain}}. {{.red}}ATTENTION{{.reset}} deletes {{.blue}}Pulumi.kube-dev.yaml{{.reset}}
    cmds:
      - |
        summonPulumi dev stack rm --emoji kube-dev
    silent: true


  pulumiStackDeleteStage:
    desc: delete the pulumi-stack for the staging-cluster for {{.domain}}. {{.red}}ATTENTION{{.reset}} deletes {{.blue}}Pulumi.kube-stage.yaml{{.reset}}
    cmds:
      - |
        summonPulumi stage stack rm --secrets-provider=passphrase --emoji kube-stage
    silent: true


  pulumiStackDeleteProd:
    desc: delete the pulumi-stack for the prod-cluster    for {{.domain}}. {{.red}}ATTENTION{{.reset}} deletes {{.blue}}Pulumi.kube-prod.yaml{{.reset}}

    cmds:
      - |
        summonPulumi prod stack rm --emoji kube-prod
    silent: true


###
##
# ** colorDisplay
#
#
  colorDisplay:
    desc: show all defined colors and their emacs-register
    cmds:
      - |
        echo -e ""
        echo -e "  {{.red}}r red{{.reset}}"
        echo -e "  {{.redLight}}e redLight{{.reset}}"
        echo -e "  {{.green}}g green{{.reset}}"
        echo -e "  {{.greenLight}}f greenLight{{.reset}}"
        echo -e "  {{.yellow}}y yellow{{.reset}}"
        echo -e "  {{.yellowLight}}t yellowLight{{.reset}}"
        echo -e "  {{.blue}}u blue{{.reset}}"
        echo -e "  {{.blueLight}}i blueLight{{.reset}}"
        echo -e "  {{.magenta}}m magenta{{.reset}}"
        echo -e "  {{.magentaLight}}j magentaLight{{.reset}}"
        echo -e "  {{.cyan}}c cyan{{.reset}}"
        echo -e "  {{.cyanLight}}d cyanLight{{.reset}}"
        echo -e "  {{.black}}b black{{.reset}}"
        echo -e "  {{.grayDark}}a grayDark{{.reset}}"
        echo -e "  {{.grayLight}}q grayLight{{.reset}}"
        echo -e "  {{.white}}w white{{.reset}}"
        echo -e ""
        echo -e "  x reset"
        echo -e ""
    silent: true


# Local Variables:
# eval: (evil-set-register  97 "{{.grayDark}}"    )  ;; a
# eval: (evil-set-register  98 "{{.black}}"       )  ;; b
# eval: (evil-set-register  99 "{{.cyan}}"        )  ;; c
# eval: (evil-set-register 100 "{{.cyanLight}}"   )  ;; d
# eval: (evil-set-register 101 "{{.redLight}}"    )  ;; e
# eval: (evil-set-register 102 "{{.greenLight}}"  )  ;; f
# eval: (evil-set-register 103 "{{.green}}"       )  ;; g
# eval: (evil-set-register 105 "{{.blueLight}}"   )  ;; i
# eval: (evil-set-register 106 "{{.magentaLight}}")  ;; j
# eval: (evil-set-register 109 "{{.magenta}}"     )  ;; m
# eval: (evil-set-register 113 "{{.grayLight}}"   )  ;; q
# eval: (evil-set-register 114 "{{.red}}"         )  ;; r
# eval: (evil-set-register 116 "{{.yellowLight}}" )  ;; t
# eval: (evil-set-register 117 "{{.blue}}"        )  ;; u
# eval: (evil-set-register 119 "{{.white}}"       )  ;; w
# eval: (evil-set-register 121 "{{.yellow}}"      )  ;; y
# eval: (evil-set-register 120 "{{.reset}}"       )  ;; x
# End:
