apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: petstore
    name: petstore
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: petstore
    template:
        metadata:
            labels:
                app: petstore
        spec:
            containers:
                - image: soloio/petstore-example:latest
                  name: petstore
                  ports:
                    - containerPort: 8080
                      name: http
