apiVersion: v1
kind: Service
metadata:
    labels:
        service: petstore
    name: petstore
    namespace: default
spec:
    ports:
        - port: 8080
          protocol: TCP
    selector:
        app: petstore
