// Code generated by "stringer -type=NamespaceTier -linecomment"; DO NOT EDIT.

package namespace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NamespaceTierAPI-0]
	_ = x[NamespaceTierApp-1]
	_ = x[NamespaceTierAuth-2]
	_ = x[NamespaceTierCommunication-3]
	_ = x[NamespaceTierDatabase-4]
	_ = x[NamespaceTierDevOps-5]
	_ = x[NamespaceTierDNS-6]
	_ = x[NamespaceTierEdge-7]
	_ = x[NamespaceTierMonitoring-8]
	_ = x[NamespaceTierProjectManagement-9]
	_ = x[NamespaceTierSecurity-10]
	_ = x[NamespaceTierStorage-11]
	_ = x[NamespaceTierTesting-12]
}

const _NamespaceTier_name = "apiappauthcommunicationdatabasedevOpsdnsedgemonitoringprojectManagementsecuritystoragetesting"

var _NamespaceTier_index = [...]uint8{0, 3, 6, 10, 23, 31, 37, 40, 44, 54, 71, 79, 86, 93}

func (i NamespaceTier) String() string {
	if i < 0 || i >= NamespaceTier(len(_NamespaceTier_index)-1) {
		return "NamespaceTier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NamespaceTier_name[_NamespaceTier_index[i]:_NamespaceTier_index[i+1]]
}
