// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Jaeger struct {
	pulumi.CustomResourceState

	ApiVersion pulumi.StringPtrOutput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrOutput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrOutput `pulumi:"metadata"`
	Spec       JaegerSpecPtrOutput        `pulumi:"spec"`
	Status     JaegerStatusPtrOutput      `pulumi:"status"`
}

// NewJaeger registers a new resource with the given unique name, arguments, and options.
func NewJaeger(ctx *pulumi.Context,
	name string, args *JaegerArgs, opts ...pulumi.ResourceOption) (*Jaeger, error) {
	if args == nil {
		args = &JaegerArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("jaegertracing.io/v1")
	args.Kind = pulumi.StringPtr("Jaeger")
	var resource Jaeger
	err := ctx.RegisterResource("kubernetes:jaegertracing.io/v1:Jaeger", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetJaeger gets an existing Jaeger resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetJaeger(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *JaegerState, opts ...pulumi.ResourceOption) (*Jaeger, error) {
	var resource Jaeger
	err := ctx.ReadResource("kubernetes:jaegertracing.io/v1:Jaeger", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Jaeger resources.
type jaegerState struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	Spec       *JaegerSpec        `pulumi:"spec"`
	Status     *JaegerStatus      `pulumi:"status"`
}

type JaegerState struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	Spec       JaegerSpecPtrInput
	Status     JaegerStatusPtrInput
}

func (JaegerState) ElementType() reflect.Type {
	return reflect.TypeOf((*jaegerState)(nil)).Elem()
}

type jaegerArgs struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	Spec       *JaegerSpec        `pulumi:"spec"`
	Status     *JaegerStatus      `pulumi:"status"`
}

// The set of arguments for constructing a Jaeger resource.
type JaegerArgs struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	Spec       JaegerSpecPtrInput
	Status     JaegerStatusPtrInput
}

func (JaegerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*jaegerArgs)(nil)).Elem()
}

type JaegerInput interface {
	pulumi.Input

	ToJaegerOutput() JaegerOutput
	ToJaegerOutputWithContext(ctx context.Context) JaegerOutput
}

func (*Jaeger) ElementType() reflect.Type {
	return reflect.TypeOf((*Jaeger)(nil))
}

func (i *Jaeger) ToJaegerOutput() JaegerOutput {
	return i.ToJaegerOutputWithContext(context.Background())
}

func (i *Jaeger) ToJaegerOutputWithContext(ctx context.Context) JaegerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(JaegerOutput)
}

type JaegerOutput struct {
	*pulumi.OutputState
}

func (JaegerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Jaeger)(nil))
}

func (o JaegerOutput) ToJaegerOutput() JaegerOutput {
	return o
}

func (o JaegerOutput) ToJaegerOutputWithContext(ctx context.Context) JaegerOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(JaegerOutput{})
}
