// Code generated by "stringer -type=IngressClassName -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IngressClassNameTraefik-0]
}

const _IngressClassName_name = "traefik"

var _IngressClassName_index = [...]uint8{0, 7}

func (i IngressClassName) String() string {
	if i < 0 || i >= IngressClassName(len(_IngressClassName_index)-1) {
		return "IngressClassName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IngressClassName_name[_IngressClassName_index[i]:_IngressClassName_index[i+1]]
}
