// Code generated by "stringer -type=ServiceKind -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceKindK8S-0]
	_ = x[ServiceKindTraefik-1]
}

const _ServiceKind_name = "ServiceTraefikService"

var _ServiceKind_index = [...]uint8{0, 7, 21}

func (i ServiceKind) String() string {
	if i < 0 || i >= ServiceKind(len(_ServiceKind_index)-1) {
		return "ServiceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceKind_name[_ServiceKind_index[i]:_ServiceKind_index[i+1]]
}
